name             'logger-server'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures logger-server'
long_description 'Installs/Configures logger-server'
version          '0.1.0'
