name             'fluentd'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures fluentd'
long_description 'Installs/Configures fluentd'
version          '0.1.0'
