name             'stun'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures stun'
long_description 'Installs/Configures stun'
version          '0.1.0'
depends          'common'
