FROM <%=node['fluentd-base']['repository']%>:<%=node['fluentd-base']['revision']%>
MAINTAINER hiroshiyui@ecoworkinc.com

ADD fluent.conf /etc/fluent/
RUN mkdir -p /var/log/fluent
RUN mkdir -p /srv/www/personal_cloud_bots/shared/log
RUN /bin/bash -l -c "gem install fluent-plugin-rewrite-tag-filter --no-ri --no-rdoc"
