name             'common'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures common'
long_description 'Installs/Configures common'
version          '0.1.0'
