FROM ecowork/fluentd
MAINTAINER hiroshiyui@ecoworkinc.com

ADD fluent.conf /etc/fluent/
ADD out_hipchatv2.rb /etc/fluent/plugin/
RUN mkdir -p /var/log/fluent /var/log/fluent/apps
RUN /bin/bash -l -c "gem install hipchat --no-ri --no-rdoc"
